INSERT INTO USER(USERNAME, PASSWORD) VALUES ('user', '$2a$10$WYecIX1wdEMLLoDGA34u/uAoOK8/uNH5HyLc02CXCgAD95f9/0Lw.');
INSERT INTO USER(USERNAME, PASSWORD) VALUES ('user2', '$2a$10$WYecIX1wdEMLLoDGA34u/uAoOK8/uNH5HyLc02CXCgAD95f9/0Lw.');
INSERT INTO ROLE(NAME) VALUES ('ROLE_USER');
INSERT INTO USERS_ROLES VALUES(1, 1);
INSERT INTO ARTICLES(AUTHOR, ENTRY_DATE, LINK, HEADLINE, VOTES, USER_ID) VALUES('Author One', CURRENT_TIMESTAMP(), 'http://google.com', 'Java 8 - Good or bad', 10, 1);
INSERT INTO ARTICLES(AUTHOR, ENTRY_DATE, LINK, HEADLINE, VOTES, USER_ID) VALUES('Author Two', CURRENT_TIMESTAMP(), 'http://google.com', 'What is Spring?', 7, 2);
INSERT INTO ARTICLES(AUTHOR, ENTRY_DATE, LINK, HEADLINE, VOTES, USER_ID) VALUES('Author Three', CURRENT_TIMESTAMP(), 'http://google.com', 'AG04 is way to go', 5, 1);
INSERT INTO ARTICLES(AUTHOR, ENTRY_DATE, LINK, HEADLINE, VOTES, USER_ID) VALUES('Author Four', CURRENT_TIMESTAMP(), 'http://facebook.com', 'Say no to Scrum', 5, 1);
INSERT INTO ARTICLES(AUTHOR, ENTRY_DATE, LINK, HEADLINE, VOTES, USER_ID) VALUES('Author Five', CURRENT_TIMESTAMP(), 'http://google.com', 'Java 8 - Good or bad', 10, 2);
INSERT INTO ARTICLES(AUTHOR, ENTRY_DATE, LINK, HEADLINE, VOTES, USER_ID) VALUES('Author Six', CURRENT_TIMESTAMP(), 'http://google.com', 'What is Spring?', 7, 2);
INSERT INTO ARTICLES(AUTHOR, ENTRY_DATE, LINK, HEADLINE, VOTES, USER_ID) VALUES('Author Seven', CURRENT_TIMESTAMP(), 'http://google.com', 'AG04 is way to go', 5, 2);
INSERT INTO ARTICLES(AUTHOR, ENTRY_DATE, LINK, HEADLINE, VOTES, USER_ID) VALUES('Author Eight', CURRENT_TIMESTAMP(), 'http://facebook.com', 'Say no to Scrum', 5, 2);
ALTER TABLE VOTES DROP CONSTRAINT FK22Y1FI7JPR4GJ0EFJJFBJ355P
ALTER TABLE VOTES ADD FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ID) ON DELETE CASCADE